TTL = 300 # Default TTL for all RRs

[A]
"google.com" = "127.0.0.1"

[NS]
"google.com" = "dns.google.com"

[CNAME]
"yahoo.com" = "google.com"

[PTR]
"8.8.8.8" = "apple.com"

[MX]
"google.com" = "mail.yahoo.com"

[TXT]
"txt.google.com" = "txt string"